In [1]:
#importing Libraries

import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
#Current wokring directory

os.getcwd()

'C:\\Users\\asqua_3jwn\\OneDrive\\Desktop\\Ananthi\\GenAI'

In [3]:
#Listing current directory

os.listdir()

['.ipynb_checkpoints', 'Datasets', 'ML_Classification_Problem.ipynb']

In [4]:
#Read the dataset

df = pd.read_csv('Datasets/ChronicKidneyDisease.csv')
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [5]:
df.tail()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [6]:
df.shape

(400, 26)

In [7]:
df.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='str')

In [8]:
#Check duplicates

df.duplicated().sum()

np.int64(0)

In [9]:
#check missing data

df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [10]:
#percentage of missing values

df.isnull().sum()/len(df) * 100

id                 0.00
age                2.25
bp                 3.00
sg                11.75
al                11.50
su                12.25
rbc               38.00
pc                16.25
pcc                1.00
ba                 1.00
bgr               11.00
bu                 4.75
sc                 4.25
sod               21.75
pot               22.00
hemo              13.00
pcv               17.50
wc                26.25
rc                32.50
htn                0.50
dm                 0.50
cad                0.50
appet              0.25
pe                 0.25
ane                0.25
classification     0.00
dtype: float64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    str
 7   pc              335 non-null    str
 8   pcc             396 non-null    str
 9   ba              396 non-null    str
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    str
 17  wc              295 non-null    str
 18  rc              270 non-null    str
 19  htn             398 non-null    str
 20  dm              398 non-null    str
 21  cad             398 non-null    str
 22  appet           399 non-null    str
 23  pe              399 non-null    str
 24  ane             399 non-null    str
 25  classification  400 non-null    str
dtypes: float64(11), int64(1), str(14)
memory usage: 81.4 KB

In [12]:
#column wise unique elements

for i in df.columns:
    print("*******************************************************",i,"**************************************************************")
    print()
    print(set(df[i].tolist()))
    print()

******************************************************* id **************************************************************

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399}

******************************************************* age **************************************************************

{2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 11.0, 12.0, 14.0, 15.0, 17.0, 19.0, 20.0, 21.0, 22.0, nan, 24.0, 23.0, 26.0, 27.0, 25.0, 29.0, 30.0, 28.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 90.0, nan, nan, nan, nan, nan, nan, nan, nan}

******************************************************* bp **************************************************************

{nan, nan, 140.0, nan, nan, nan, nan, 50.0, 180.0, 60.0, 70.0, nan, 80.0, nan, nan, 90.0, nan, 100.0, 110.0, nan, nan, 120.0}

******************************************************* sg **************************************************************

{1.02, 1.005, 1.015, 1.01, 1.025, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

******************************************************* al **************************************************************

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

******************************************************* su **************************************************************

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

******************************************************* rbc **************************************************************

{nan, 'abnormal', 'normal'}

******************************************************* pc **************************************************************

{nan, 'abnormal', 'normal'}

******************************************************* pcc **************************************************************

{nan, 'present', 'notpresent'}

******************************************************* ba **************************************************************

{nan, 'present', 'notpresent'}

******************************************************* bgr **************************************************************

{22.0, nan, nan, 70.0, 74.0, 75.0, 76.0, 78.0, nan, 79.0, 80.0, 82.0, 81.0, 84.0, 85.0, 86.0, 83.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 116.0, 117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 124.0, 125.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 137.0, 138.0, 139.0, 140.0, nan, 141.0, 143.0, 144.0, 146.0, nan, 148.0, 150.0, nan, 153.0, 156.0, 157.0, 158.0, 159.0, 160.0, 162.0, 163.0, nan, 165.0, 169.0, 171.0, 172.0, 173.0, 176.0, nan, 182.0, nan, 184.0, 192.0, nan, nan, nan, 201.0, 203.0, 204.0, nan, 207.0, 208.0, 210.0, nan, 214.0, 213.0, 215.0, nan, 219.0, 220.0, 224.0, 226.0, 230.0, nan, 233.0, 234.0, 238.0, 239.0, 241.0, 242.0, 246.0, nan, 248.0, 250.0, 251.0, 252.0, 253.0, 255.0, 256.0, 261.0, 263.0, 264.0, nan, nan, 268.0, 269.0, 270.0, nan, 273.0, nan, 280.0, nan, 288.0, 294.0, 295.0, 297.0, 298.0, nan, 303.0, 307.0, 308.0, 309.0, nan, 323.0, nan, 341.0, nan, 352.0, nan, nan, nan, nan, 360.0, nan, nan, 380.0, nan, nan, nan, nan, nan, 410.0, nan, nan, 415.0, 423.0, 424.0, 425.0, nan, nan, 87.0, 447.0, nan, 463.0, nan, 490.0, nan}

******************************************************* bu **************************************************************

{1.5, 10.0, nan, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 50.1, 58.0, 57.0, 60.0, 61.0, 64.0, 65.0, 66.0, 67.0, 68.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 79.0, 80.0, nan, 82.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 92.0, 93.0, 94.0, 95.0, 96.0, 98.0, 98.6, 103.0, 106.0, 107.0, 111.0, 113.0, 114.0, 115.0, nan, 118.0, 125.0, 132.0, 133.0, nan, 137.0, 139.0, 142.0, 145.0, 146.0, 148.0, 150.0, nan, 153.0, 155.0, 158.0, 162.0, 163.0, 164.0, 165.0, 166.0, nan, 176.0, 180.0, 186.0, 191.0, 202.0, 208.0, nan, 215.0, 217.0, 219.0, nan, 223.0, nan, 235.0, 241.0, nan, nan, nan, nan, nan, nan, 309.0, 322.0, nan, 391.0, nan, nan, nan}

******************************************************* sc **************************************************************

{0.8, 1.2, 1.4, 3.8, 1.8, 1.1, 1.9, 7.2, 4.0, 2.7, 2.1, 4.6, 4.1, 9.6, 5.2, 7.7, 7.3, 2.5, 2.0, 10.8, 3.0, 3.25, 15.0, 14.2, 24.0, 16.9, 18.0, 18.1, 1.5, 1.0, 32.0, 6.5, 0.5, 6.0, 7.5, 8.5, 48.1, 11.5, 12.0, 13.0, 13.5, 76.0, 16.4, nan, 2.4, 2.9, 3.9, 3.4, 4.4, 5.9, 6.4, nan, 11.9, 13.4, nan, 2.8, 2.3, 3.3, nan, 4.3, 1.3, 5.3, 6.3, 6.8, 0.6, 0.9, 0.4, nan, nan, nan, nan, 9.7, 9.2, 9.3, 0.7, 10.2, 1.7, 11.8, 12.2, 12.8, nan, 13.8, 13.3, 2.2, 15.2, 3.2, nan, nan, 6.7, nan, 5.6, 6.1, 7.1, 1.6, 2.6, 3.6, nan, nan, nan, nan, nan}

******************************************************* sod **************************************************************

{4.5, nan, nan, nan, nan, nan, nan, nan, nan, nan, 104.0, nan, 111.0, nan, 113.0, 114.0, 115.0, nan, 120.0, 122.0, nan, 124.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 139.0, 140.0, 141.0, 142.0, nan, 143.0, nan, 146.0, 147.0, 145.0, nan, nan, 150.0, 144.0, nan, nan, nan, 163.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

******************************************************* pot **************************************************************

{2.5, 3.2, 4.0, 3.7, 4.2, 5.8, 3.4, 6.4, 4.9, 4.1, 4.3, 5.2, 5.9, nan, 3.5, 3.0, nan, 4.5, 5.5, 5.0, nan, nan, 6.5, nan, nan, 39.0, nan, nan, 47.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 2.9, nan, nan, 3.9, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 4.4, nan, 5.4, nan, nan, nan, nan, nan, nan, 2.8, nan, 3.8, 3.3, 4.8, 5.3, 6.3, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 2.7, nan, nan, nan, nan, 4.7, nan, 5.7, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 4.6, nan, nan, nan, 5.1, 5.6, 6.6, nan, 7.6, nan, nan, 3.6, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

******************************************************* hemo **************************************************************

{3.1, 4.8, 5.6, 6.6, 7.6, 7.7, 9.6, 10.8, 11.2, 11.3, 11.6, 12.2, 15.4, 12.4, 9.5, 9.4, 12.6, 12.1, 12.7, 15.0, 15.6, 16.1, nan, 5.5, 6.0, 7.5, 8.0, 8.5, 9.0, 10.0, 10.5, nan, 11.0, 11.5, 12.5, 12.0, nan, 13.0, 13.5, nan, 14.0, 14.5, nan, nan, 15.5, nan, 16.5, 16.4, 16.9, 16.0, 16.6, 17.0, 17.1, 17.4, 17.5, 17.6, nan, nan, nan, nan, nan, nan, nan, nan, nan, 7.9, nan, 8.4, 9.9, 10.4, 10.9, nan, nan, 11.9, 11.4, 12.9, nan, 13.9, 13.4, 14.4, 14.9, 15.9, nan, nan, nan, 5.8, 6.8, 6.3, 7.3, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 8.3, 8.2, 8.7, 8.8, 9.7, 9.8, 9.3, 9.2, 10.3, 10.2, 10.7, 11.8, 11.7, nan, 12.3, 12.8, nan, 13.2, 13.8, 13.7, nan, nan, 14.3, 14.2, 14.8, 13.3, nan, 15.2, 15.7, 14.7, 15.8, 15.3, 16.2, 16.3, nan, 16.7, 16.8, 17.2, 17.3, 17.7, 17.8, 6.2, nan, nan, nan, nan, nan, nan, nan, 6.1, 7.1, nan, 8.6, 8.1, nan, 9.1, nan, 10.1, 10.6, 11.1, 13.6, 13.1, 14.1, 14.6, 15.1, nan, nan}

******************************************************* pcv **************************************************************

{'34', '51', '32', '43', '15', '31', '27', '40', '37', '9', '25', '14', '17', '36', '52', '46', '42', '50', '16', '24', '30', '20', '28', '49', '44', '33', '\t?', '41', '18', nan, '\t43', '29', '35', '19', '21', '53', '45', '48', '26', '47', '38', '22', '39', '54', '23'}

******************************************************* wc **************************************************************

{'10200', '11300', '9900', '10500', '5000', '7900', '\t6200', '9500', '11200', '6700', '7500', '11500', '5100', '6800', '12800', '12500', '9200', '4900', '2200', '10900', '11000', '9600', '10300', '14600', '9000', '8400', '2600', '26400', '9100', '6000', '16300', '6200', '9700', '5700', '12100', '13200', '4100', '8300', '4300', '10800', '9400', '7700', '\t?', nan, '8000', '5600', '4200', '21600', '8600', '12700', '11400', '15700', '7200', '19100', '10400', '9800', '15200', '5300', '7100', '5500', '12200', '9300', '7400', '7000', '5900', '7300', '12400', '8100', '5400', '8800', '14900', '8200', '6300', '13600', '4700', '11800', '4500', '6600', '11900', '5200', '3800', '6400', '7800', '18900', '8500', '12300', '\t8400', '16700', '12000', '10700', '6900', '5800', '6500'}

******************************************************* rc **************************************************************

{'3.4', '4.5', '3.8', '3.0', '4.9', '4.2', '3.1', '5.4', '4.1', '2.3', '2.7', '2.6', '5.0', '3.3', '4.8', '2.9', '5.1', '8.0', '6.3', '5.5', '3.6', '3.2', '2.5', '2.1', '4.6', '6.0', '5.3', '5.8', '5.6', '4', '3.5', '6.5', '6.2', '6.1', '\t?', '2.8', '2.4', nan, '3', '5', '4.7', '5.7', '3.9', '4.3', '5.9', '5.2', '4.0', '3.7', '4.4', '6.4'}

******************************************************* htn **************************************************************

{'no', nan, 'yes'}

******************************************************* dm **************************************************************

{'yes', '\tyes', ' yes', '\tno', nan, 'no'}

******************************************************* cad **************************************************************

{'\tno', 'no', nan, 'yes'}

******************************************************* appet **************************************************************

{nan, 'poor', 'good'}

******************************************************* pe **************************************************************

{'no', nan, 'yes'}

******************************************************* ane **************************************************************

{'no', nan, 'yes'}

******************************************************* classification **************************************************************

{'ckd', 'notckd', 'ckd\t'}

In [13]:
df['pcv'].mode()[0]

'41'

In [14]:
#convert str to numbers because of few string values,so its in str

df['pcv'] = df['pcv'].apply(lambda x:'43' if x=='\t43' else x)
df['pcv'] = df['pcv'].apply(lambda x:'41' if x=='\t?' else x)

In [15]:
df['wc'].mode()[0]

'9800'

In [16]:
df['wc'] = df['wc'].apply(lambda x:'8400' if x=='\t8400' else x)
df['wc'] = df['wc'].apply(lambda x:'9800' if x=='\t?' else x)
df['wc'] = df['wc'].apply(lambda x:'6200' if x=='\t6200' else x)

In [17]:
df['rc'].mode()[0]

'5.2'

In [18]:
df['rc'] = df['rc'].apply(lambda x:'5.2' if x=='\t?' else x)

In [19]:
df['classification'] = df['classification'].apply(lambda x:'ckd' if x=='ckd\t' else x)

In [20]:
df['dm'] = df['dm'].apply(lambda x:'yes' if x=='\tyes' else x)
df['dm'] = df['dm'].apply(lambda x:'no' if x=='\tno' else x)
df['dm'] = df['dm'].apply(lambda x:'yes' if x==' yes' else x)

In [21]:
df['cad'] = df['cad'].apply(lambda x:'no' if x=='\tno' else x)

In [22]:
print(df['pcv'].mode()[0])
print(df['wc'].mode()[0])
print(df['rc'].mode()[0])

41
9800
5.2

In [23]:
#filling missing values on the above variable/attribute to nan value 

df['pcv'] = df['pcv'].fillna(df['pcv'].mode()[0])
df['wc'] = df['wc'].fillna(df['wc'].mode()[0])
df['rc'] = df['rc'].fillna(df['rc'].mode()[0])

In [24]:
#convert it to number

df['pcv']=df['pcv'].astype('int64')
df['wc']=df['wc'].astype('int64')
df['rc']=df['rc'].astype('float64')

In [25]:
#pcv,wc,rc converted to numbers because we can see in dataset those are in numbers but mark it as str, so we converted

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    str
 7   pc              335 non-null    str
 8   pcc             396 non-null    str
 9   ba              396 non-null    str
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             400 non-null    int64
 17  wc              400 non-null    int64
 18  rc              400 non-null    float64
 19  htn             398 non-null    str
 20  dm              398 non-null    str
 21  cad             398 non-null    str
 22  appet           399 non-null    str
 23  pe              399 non-null    str
 24  ane             399 non-null    str
 25  classification  400 non-null    str
dtypes: float64(12), int64(3), str(11)
memory usage: 81.4 KB

In [26]:
for i in df.select_dtypes(exclude=['object']).columns:
    df[i] = df[i].apply(lambda x:float(x))

In [27]:
object_columns= df.select_dtypes(include=['object']).columns
print("Object Data type columns: ")
print(object_columns)

Object Data type columns:
Index(['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane',
       'classification'],
      dtype='str')

In [28]:
numerical_columns=df.select_dtypes(include=['int64','float64']).columns
print("Numerical Data Type columns: ")
print(numerical_columns)

Numerical Data Type columns:
Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo', 'pcv', 'wc', 'rc'],
      dtype='str')

In [29]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\asqua_3jwn\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\asqua_3jwn\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\asqua_3jwn\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\asqua_3jwn\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\asqua_3jwn\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [30]:
# Handling or filling missing values by using SimpleImputer techniques (Nan values need to fill)

from sklearn.impute import SimpleImputer

imp_1= SimpleImputer(missing_values=np.nan, strategy="most_frequent")
imp_2= SimpleImputer(missing_values=np.nan, strategy="median")

df_imp_1=pd.DataFrame(imp_1.fit_transform(df[object_columns]))
df_imp_1.columns=df[object_columns].columns

df_imp_2=pd.DataFrame(imp_2.fit_transform(df[numerical_columns]))
df_imp_2.columns=df[numerical_columns].columns

#checking if there is any null value
print(df_imp_1.isnull().sum())
print()
print(df_imp_2.isnull().sum())

rbc               0
pc                0
pcc               0
ba                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

id      0
age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
pcv     0
wc      0
rc      0
dtype: int64

In [31]:
#checking if there any null values for example

for i in df_imp_2['sg']:
    print(i)

1.02
1.02
1.01
1.005
1.01
1.015
1.01
1.015
1.015
1.02
1.01
1.01
1.015
1.02
1.01
1.015
1.015
1.02
1.025
1.015
1.015
1.02
1.025
1.01
1.015
1.025
1.015
1.01
1.02
1.005
1.02
1.015
1.01
1.02
1.01
1.02
1.015
1.02
1.02
1.01
1.01
1.01
1.01
1.01
1.01
1.02
1.015
1.01
1.005
1.01
1.02
1.015
1.015
1.015
1.01
1.005
1.015
1.02
1.02
1.02
1.02
1.01
1.02
1.015
1.01
1.01
1.02
1.02
1.01
1.015
1.015
1.01
1.01
1.015
1.015
1.015
1.005
1.01
1.02
1.01
1.01
1.02
1.02
1.015
1.01
1.015
1.02
1.005
1.01
1.02
1.01
1.015
1.01
1.01
1.01
1.015
1.01
1.015
1.02
1.02
1.015
1.015
1.01
1.015
1.02
1.015
1.02
1.015
1.015
1.02
1.015
1.01
1.015
1.015
1.015
1.01
1.015
1.02
1.01
1.01
1.025
1.02
1.02
1.015
1.015
1.02
1.015
1.015
1.015
1.025
1.01
1.01
1.02
1.015
1.01
1.015
1.02
1.01
1.01
1.015
1.01
1.01
1.02
1.015
1.01
1.015
1.01
1.01
1.02
1.02
1.025
1.02
1.01
1.01
1.005
1.02
1.015
1.025
1.02
1.01
1.02
1.015
1.02
1.01
1.015
1.02
1.02
1.02
1.015
1.01
1.015
1.02
1.01
1.015
1.02
1.01
1.01
1.015
1.02
1.01
1.01
1.025
1.02
1.015
1.015
1.02
1.02
1.01
1.02
1.01
1.01
1.01
1.015
1.025
1.01
1.02
1.01
1.02
1.02
1.015
1.025
1.02
1.02
1.02
1.01
1.02
1.01
1.01
1.02
1.02
1.015
1.015
1.015
1.01
1.015
1.01
1.01
1.01
1.015
1.01
1.01
1.02
1.02
1.01
1.02
1.01
1.015
1.015
1.02
1.01
1.01
1.02
1.015
1.015
1.01
1.01
1.02
1.015
1.02
1.015
1.015
1.015
1.01
1.02
1.015
1.02
1.015
1.025
1.01
1.01
1.025
1.025
1.025
1.025
1.025
1.025
1.025
1.02
1.02
1.02
1.02
1.02
1.02
1.02
1.02
1.02
1.02
1.025
1.02
1.025
1.025
1.025
1.025
1.02
1.02
1.02
1.025
1.025
1.02
1.025
1.02
1.025
1.02
1.02
1.025
1.02
1.02
1.025
1.025
1.02
1.02
1.025
1.02
1.02
1.02
1.02
1.02
1.025
1.02
1.02
1.02
1.025
1.02
1.02
1.025
1.02
1.02
1.02
1.025
1.02
1.02
1.025
1.02
1.02
1.025
1.025
1.02
1.02
1.025
1.02
1.02
1.02
1.02
1.025
1.02
1.02
1.02
1.025
1.02
1.025
1.02
1.025
1.025
1.02
1.025
1.02
1.02
1.025
1.02
1.02
1.025
1.025
1.02
1.025
1.02
1.025
1.02
1.025
1.02
1.025
1.025
1.02
1.02
1.02
1.025
1.02
1.025
1.025
1.02
1.02
1.025
1.02
1.025
1.025
1.025
1.02
1.025
1.025
1.025
1.02
1.02
1.025
1.02
1.025
1.025
1.02
1.025
1.02
1.025
1.025
1.02
1.025
1.025
1.025
1.02
1.02
1.025
1.025
1.02
1.025
1.025
1.025
1.02
1.025
1.02
1.02
1.025
1.02
1.025
1.025

In [32]:
df_imp_1.head()

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd

In [33]:
df_imp_2.head()

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,0.0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2
1,1.0,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,5.2
2,2.0,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,5.2
3,3.0,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
4,4.0,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6

In [34]:
#Removing ID column because it is not significant column
df_imp_2 = df_imp_2.iloc[:,1:]

In [35]:
df_imp_2.head()

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,5.2
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,5.2
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6

In [36]:
#create same column name on both dataframes and combine using same column name

df_imp_1['test'] = 'test'
df_imp_2['test'] = 'test'

In [37]:
df_imp_1.head()

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification,test
0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd,test
1,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd,test
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd,test
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd,test
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd,test

In [38]:
#combine both tables with column wise using axis=1

table_df = pd.concat([df_imp_1,df_imp_2],axis=1)
table_df.head()

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,...,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,test
0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,...,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2,test
1,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,5.2,test
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,...,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,5.2,test
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,...,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,test
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6,test

In [39]:
table_df.columns

Index(['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane',
       'classification', 'test', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'test'],
      dtype='str')

In [40]:
table_df = table_df.drop(['test'], axis=1)
table_df.columns

Index(['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane',
       'classification', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc',
       'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc'],
      dtype='str')

In [41]:
#split the data into independent variable and dependent variable

x = table_df.drop('classification', axis=1)
y = table_df['classification']

In [42]:
#Independent variable
x

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,...,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,...,0.0,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2
1,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,5.2
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,...,3.0,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,5.2
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,...,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9
396,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,7800.0,6.2
397,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4
398,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9
399,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1

In [43]:
#Dependent variable
y

0         ckd
1         ckd
2         ckd
3         ckd
4         ckd
        ...
395    notckd
396    notckd
397    notckd
398    notckd
399    notckd
Name: classification, Length: 400, dtype: str

In [44]:
y.value_counts()

classification
ckd       250
notckd    150
Name: count, dtype: int64

In [45]:
y

0         ckd
1         ckd
2         ckd
3         ckd
4         ckd
        ...
395    notckd
396    notckd
397    notckd
398    notckd
399    notckd
Name: classification, Length: 400, dtype: str

In [46]:
y = np.where(y == 'ckd', 1, 0)

In [47]:
pd.DataFrame(y).value_counts()

0
1    250
0    150
Name: count, dtype: int64

In [48]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [49]:
x.head()

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,...,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,...,0.0,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2
1,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,5.2
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,...,3.0,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,5.2
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,...,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,...,0.0,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6

In [65]:
#convert these char to numbers like rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane coobject_columns

#Handling Encoding part of x 
#label encoder and one hot encoder in ML

def classify_features(x):
    categorical_features=[]
    non_categorical_features=[]
    discreate_features=[]
    continuous_features=[]
    for column in x.columns:
        if x[column].dtype == 'str':
            if x[column].nunique()<3:
                categorical_features.append(column)
            else:
                non_categorical_features.append(column)
        elif x[column].dtype in ['float64','int64']:
            if x[column].nunique() < 100:
                discreate_features.append(column)
            else:
                continuous_features.append(column)
    return categorical_features, non_categorical_features, discreate_features, continuous_features

In [66]:
categorical_features, non_categorical_features, discreate_features, continuous_features = classify_features(x)

In [67]:
categorical_features

['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']

In [68]:
non_categorical_features

[]

In [69]:
discreate_features

['age', 'bp', 'sg', 'al', 'su', 'sc', 'sod', 'pot', 'pcv', 'wc', 'rc']

In [70]:
continuous_features

['bgr', 'bu', 'hemo']

In [74]:
#Exploratory Data Analysis (EDA)

import dtale
dtale.show(df)

In [75]:
df_dummies = pd.get_dummies(x[categorical_features], drop_first=True)

In [76]:
x[categorical_features]

        rbc        pc         pcc          ba  htn   dm cad appet   pe  ane
0    normal    normal  notpresent  notpresent  yes  yes  no  good   no   no
1    normal    normal  notpresent  notpresent   no   no  no  good   no   no
2    normal    normal  notpresent  notpresent   no  yes  no  poor   no  yes
3    normal  abnormal     present  notpresent  yes   no  no  poor  yes  yes
4    normal    normal  notpresent  notpresent   no   no  no  good   no   no
..      ...       ...         ...         ...  ...  ...  ..   ...  ...  ...
395  normal    normal  notpresent  notpresent   no   no  no  good   no   no
396  normal    normal  notpresent  notpresent   no   no  no  good   no   no
397  normal    normal  notpresent  notpresent   no   no  no  good   no   no
398  normal    normal  notpresent  notpresent   no   no  no  good   no   no
399  normal    normal  notpresent  notpresent   no   no  no  good   no   no

[400 rows x 10 columns]

In [77]:
df_dummies

,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
0,True,True,False,False,True,True,False,False,False,False
1,True,True,False,False,False,False,False,False,False,False
2,True,True,False,False,False,True,False,True,False,True
3,True,False,True,False,True,False,False,True,True,True
4,True,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
395,True,True,False,False,False,False,False,False,False,False
396,True,True,False,False,False,False,False,False,False,False
397,True,True,False,False,False,False,False,False,False,False
398,True,True,False,False,False,False,False,False,False,False
399,True,True,False,False,False,False,False,False,False,False

In [78]:
df_dummies1 = np.where(df_dummies[0:]==True, 1, 0)

In [79]:
df_dummies1

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]], shape=(400, 10))

In [80]:
df_dummies1 = pd.DataFrame(df_dummies1)
df_dummies1.columns = df_dummies.columns

In [81]:
df_dummies1

,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
0,1,1,0,0,1,1,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0
2,1,1,0,0,0,1,0,1,0,1
3,1,0,1,0,1,0,0,1,1,1
4,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
395,1,1,0,0,0,0,0,0,0,0
396,1,1,0,0,0,0,0,0,0,0
397,1,1,0,0,0,0,0,0,0,0
398,1,1,0,0,0,0,0,0,0,0
399,1,1,0,0,0,0,0,0,0,0

In [82]:
x1 = pd.concat([x.drop(columns=categorical_features), df_dummies1], axis=1)

In [83]:
x1

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,...,1,1,0,0,1,1,0,0,0,0
1,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,...,1,1,0,0,0,0,0,0,0,0
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,...,1,1,0,0,0,1,0,1,0,1
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,...,1,0,1,0,1,0,0,1,1,1
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,...,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,...,1,1,0,0,0,0,0,0,0,0
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,...,1,1,0,0,0,0,0,0,0,0
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,...,1,1,0,0,0,0,0,0,0,0
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,...,1,1,0,0,0,0,0,0,0,0
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,...,1,1,0,0,0,0,0,0,0,0

In [84]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [95]:
#Split the data into training and testing 

#For training 70-80% data, For testing 30-20% data from the dataset

#random state will fix the train dataset as a same rows 80%(default rows). it will not change.
#stratify used for imbalanced data

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1, y, test_size=0.2, random_state=42, stratify=y)

In [96]:
x_train

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
108,45.0,80.0,1.015,0.0,0.0,107.0,15.0,1.0,141.0,4.2,...,1,0,0,0,0,0,0,0,0,0
210,59.0,100.0,1.015,4.0,2.0,255.0,132.0,12.8,135.0,5.7,...,1,1,0,0,1,1,1,0,0,1
137,45.0,60.0,1.010,2.0,0.0,268.0,86.0,4.0,134.0,5.1,...,1,0,1,0,1,1,0,0,0,0
148,69.0,60.0,1.020,0.0,0.0,171.0,26.0,48.1,138.0,4.4,...,1,1,0,0,1,0,0,1,0,0
246,48.0,110.0,1.015,3.0,0.0,106.0,215.0,15.2,120.0,5.7,...,0,1,1,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,47.0,100.0,1.010,0.0,0.0,204.0,29.0,1.0,139.0,4.2,...,1,1,0,0,1,0,0,0,0,1
346,33.0,60.0,1.020,0.0,0.0,130.0,41.0,0.9,141.0,4.4,...,1,1,0,0,0,0,0,0,0,0
20,61.0,80.0,1.015,2.0,0.0,173.0,148.0,3.9,135.0,5.2,...,0,0,0,0,1,1,1,1,1,1
144,60.0,90.0,1.010,2.0,0.0,105.0,53.0,2.3,136.0,5.2,...,0,1,0,0,0,0,0,0,0,0
370,69.0,70.0,1.020,0.0,0.0,83.0,42.0,1.2,139.0,3.7,...,1,1,0,0,0,0,0,0,0,0

In [97]:
x_test

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
342,44.0,60.0,1.020,0.0,0.0,95.0,46.0,0.5,138.0,4.2,...,1,1,0,0,0,0,0,0,0,0
204,65.0,90.0,1.010,4.0,2.0,172.0,82.0,13.5,145.0,6.3,...,1,1,0,0,1,1,0,0,1,1
233,51.0,100.0,1.015,2.0,0.0,93.0,20.0,1.6,146.0,4.5,...,1,1,0,1,0,0,0,1,0,0
366,60.0,80.0,1.025,0.0,0.0,81.0,15.0,0.5,141.0,3.6,...,1,1,0,0,0,0,0,0,0,0
120,72.0,90.0,1.025,1.0,3.0,323.0,40.0,2.2,137.0,5.3,...,1,1,0,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,52.0,90.0,1.015,4.0,3.0,224.0,166.0,5.6,133.0,47.0,...,1,0,0,0,1,1,0,0,0,1
353,39.0,60.0,1.020,0.0,0.0,86.0,37.0,0.6,150.0,5.0,...,1,1,0,0,0,0,0,0,0,0
44,54.0,80.0,1.010,3.0,0.0,207.0,77.0,6.3,134.0,4.8,...,0,0,0,0,1,1,0,1,1,0
171,83.0,70.0,1.020,3.0,0.0,102.0,60.0,2.6,115.0,5.7,...,1,1,0,0,1,0,0,1,0,1
298,34.0,60.0,1.020,0.0,0.0,91.0,49.0,1.2,135.0,4.5,...,1,1,0,0,0,0,0,0,0,0

In [98]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [99]:
y_test

array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [100]:
pd.DataFrame(y_train).value_counts()

0
1    200
0    120
Name: count, dtype: int64

In [101]:
pd.DataFrame(y_test).value_counts()

0
1    50
0    30
Name: count, dtype: int64

In [ ]:
#Build a model using pycaret (one of the low code mclassmethod)
#https://pycaret.readthedocs.io/en/latest/index.html
#we have to go other method now

In [102]:
#Building RandomForest  Classification MUnicodeTranslateError
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [103]:
#Prediction

y_prediction = model.predict(x_test)

In [106]:
x_test.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo',
       'pcv', 'wc', 'rc', 'rbc_normal', 'pc_normal', 'pcc_present',
       'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_poor', 'pe_yes',
       'ane_yes'],
      dtype='str')

In [107]:
y_test

array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [108]:
y_prediction

array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [113]:
#Evaluate the model accuracy

from sklearn.metrics import accuracy_score, classification_report

In [111]:
accuracy_score(y_test,y_prediction)

1.0

In [112]:
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        50

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80